version: '3.9'
services: 

  nginx:
    extends:
      file: ./services.yml
      service: nginx
    environment:
      - NGINX_HOST_API=http://host.docker.internal:3000
      - NGINX_HOST_WEB=http://host.docker.internal:3000
      - NGINX_LOCALHOST=http://host.docker.internal
    ports:
      - 80:80